# This script was generated by OpenMMDL-Setup on 2023-01-19.


        #       ,-----.    .-------.     .-''-.  ,---.   .--.,---.    ,---.,---.    ,---. ______       .---.      
        #     .'  .-,  '.  \  _(`)_ \  .'_ _   \ |    \  |  ||    \  /    ||    \  /    ||    _ `''.   | ,_|      
        #    / ,-.|  \ _ \ | (_ o._)| / ( ` )   '|  ,  \ |  ||  ,  \/  ,  ||  ,  \/  ,  || _ | ) _  \,-./  )      
        #   ;  \  '_ /  | :|  (_,_) /. (_ o _)  ||  |\_ \|  ||  |\_   /|  ||  |\_   /|  ||( ''_'  ) |\  '_ '`)    
        #   |  _`,/ \ _/  ||   '-.-' |  (_,_)___||  _( )_\  ||  _( )_/ |  ||  _( )_/ |  || . (_) `. | > (_)  )    
        #   : (  '\_/ \   ;|   |     '  \   .---.| (_ o _)  || (_ o _) |  || (_ o _) |  ||(_    ._) '(  .  .-'    
        #    \ `"/  \  ) / |   |      \  `-'    /|  (_,_)\  ||  (_,_)  |  ||  (_,_)  |  ||  (_.\.' /  `-'`-'|___  
        #     '. \_/``".'  /   )       \       / |  |    |  ||  |      |  ||  |      |  ||       .'    |        \ 
        #       '-----'    `---'        `'-..-'  '--'    '--''--'      '--''--'      '--''-----'`      `--------` 
                                                                                                      
                                                                                                      
    
#!/bin/sh

# Input
#comp_file= # the file name of complex that contains all components to be modelled 


################################## Receptor ######################################
rcp_nm=protein # the file name of ligand without suffix `pdb`
rcp_ff=leaprc.protein.ff14SB


## Clean the PDB file by pdb4amber
pdb4amber -i ${rcp_nm}.pdb -o ${rcp_nm}_amber.pdb

## `tleap` requires that all residues and atoms have appropriate types to ensure compatibility with the specified force field.
## To avoid `tleap` failing, we delete non-essential atoms, such as hydrogens, but preserve important atoms like carbon and nitrogen within the caps residues.
## Don' worry about the missing atoms as tleap has the capability to reconstruct them automatically. 
awk '! ($2 ~ "(CH3|HH31|HH32|HH33)" || $3 ~ "(CH3|HH31|HH32|HH33)" )' ${rcp_nm}_amber.pdb > ${rcp_nm}_amber_f.pdb
 
################################## Ligand ######################################
# Normal Ligand
nmLigFile=ligand # the file name of ligand without suffix `pdb`
charge_method=bcc # refers to the charge method that antechamber will adopt
charge_value=2 # Enter the net molecular charge of the ligand as integer (e.g. 1 or -2)
lig_ff=gaff # Ligand force field 

## Clean the PDB file by pdb4amber
pdb4amber -i ${nmLigFile}.pdb -o ${nmLigFile}_amber.pdb

## Generate a prepc file and an additional frcmod file by `antechamber`
antechamber -fi pdb -fo prepc -i ${nmLigFile}_amber.pdb -o ${nmLigFile}.prepc -c ${charge_method} -at ${lig_ff} -nc ${charge_value} -pf y
parmchk2 -f prepc -i ${nmLigFile}.prepc -o ${nmLigFile}.frcmod

## Rename ligand pdb
antechamber -i ${nmLigFile}.prepc -fi prepc -o rename_${nmLigFile}.pdb -fo pdb
# Special Ligand
spLigFile=hem # the file name of ligand without suffix `pdb`
prepc=heme_all-atom # the file name without suffix `prepc`
frcmod=heme_all-atom # the file name without suffix `frcmod`

## Clean the PDB file by pdb4amber
pdb4amber -i ${spLigFile}.pdb -o ${spLigFile}_amber.pdb

######################  Combine All Components to Be Modelled ####################
cat > tleap.combine.in <<EOF

rcp = loadpdb ${rcp_nm}_amber_f.pdb
nmLig = loadpdb rename_${nmLigFile}.pdb 
spLig = loadpdb ${spLigFile}_amber.pdb 
comp = combine{rcp nmLig spLig}
savepdb comp comp.pdb

quit

EOF

tleap -s -f tleap.combine.in > tleap.combine.out

################################ Add Water/Membrane ##############################
boxType=solvatebox # `solvatebox`, a command in tleap, creates a cubic box 
dist=10 # the minimum distance between any atom originally present in solute and the edge of the periodic box.
water_ff=tip3p
solvent=TIP3PBOX  # set the water box
pos_ion=Na+
neg_ion=Cl-
numIon=0 # `numIon` is the flag for `addions` in tleap. When set to 0, the system will be neutralized


##################### Generate Prmtop and Frcmod File for the Complex ###################### 
cat > tleap.in <<EOF

source ${rcp_ff}
source leaprc.water.${water_ff}
source leaprc.${lig_ff}

loadamberprep ${nmLigFile}.prepc
loadamberparams ${nmLigFile}.frcmod

loadamberprep ${prepc}.prepc
loadamberparams ${frcmod}.frcmod

system = loadpdb comp.pdb

solvatebox system ${solvent} ${dist} 
addions2 system ${neg_ion} ${numIon}
addions2 system ${pos_ion} ${numIon}
check system 
charge system

savepdb system system.${water_ff}.pdb
saveamberparm system system.${water_ff}.prmtop system.${water_ff}.inpcrd

quit

EOF

tleap -s -f tleap.in > tleap.out