name: docs

channels:
  - conda-forge  # Add the conda-forge channel here
  - nodefaults

dependencies:
  - pip
  - setuptools>=61.0
  - versioningit~=2.0
  - pytest>=6.1.2
  - pytest-runner
  - numpy
  - plip
  - requests>=2.28.1
  - rdkit>=2022.03.5
  - mdtraj
  - pdbfixer
  - openff-toolkit
  - openmmforcefields
  - cudatoolkit>=11.7.0
  - cuda-python>=11.7.1
  - mdanalysis>=2.3.0
  - pytest-shutil>=1.7.0
  - flask>=2.2.2
  - cairosvg
  - nglview
  - mdonatello
  - numba>=0.59.1
  - jupyter


